Rails.application.routes.draw do
  
  get 'sessions/new', to: 'sessions#new'
  post 'sessions/create', to: 'sessions#create'
  delete 'sessions/destroy', to: 'sessions#destroy'
  #JBV - Routes autogenerated for each 'action' for each 'object' by the 'rails generate scaffold' commands
  resources :gossip_tags
  resources :likes
  resources :private_messages
  resources :comments
  resources :tags
  resources :gossips
  resources :cities
  resources :users

  # JBV - Route (GET) to the root of the web site
  get "/", to: 'gossips#index'
  
  # JBV - Route (GET) to the "team.html.erb" template - Page showing the team members
  get "/team", to: 'static_pages#team'

  # JBV - Route (GET) to the  "contact.html.erb" template - Page showing the contact page (TO DO: add a contact form?)
  get "/contact", to: 'static_pages#contact'

   # JBV - Dynamic route (GET) to the "welcome.html.erb" template - Page saying a personalized hello to ':user_name''
   get "/welcome/:first_name", to: 'dynamic_pages#welcome'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
